// Range FEA Windows application icon generator.
// range-fea.svg follows the macOS icon grid (rounded square of 824/1024 with a
// transparent margin reserved for the system shadow), which makes it look too
// small next to other Windows icons. This script derives a Windows variant that
// fills the whole canvas with a smaller Fluent-like corner radius, and renders it
// into range-fea.ico and the MSIX assets in ./msix. range-fea.svg and
// range-fea.icns are left untouched and keep being used on macOS.
// Sizes of 32 px and below are drawn with a heavier outline so the triangle
// stays readable instead of dissolving into the gradient.
// Rendering uses headless Microsoft Edge (or Chrome), so it runs on Windows.
// Usage: node generate_app_icons.js
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const OUT = __dirname;

// Geometry of the macOS icon: the rounded square spans 97.5..926.5.
const MAC_MIN = 97.5, MAC_SIZE = 829;
// Windows icon: nearly full bleed, 1.5 % margin so the anti-aliased edge is not clipped.
const WIN_MARGIN = 16, WIN_RADIUS = 160;
const SCALE = (1024 - 2 * WIN_MARGIN) / MAC_SIZE;

function windowsSvg({ stroke, node }) {
  const f = n => +n.toFixed(3);
  const r = f(WIN_RADIUS / SCALE);
  const h = node / 2;
  // Triangle corners of the original glyph (already shifted down by 25).
  const top = [512, 275], left = [285.101, 668], right = [738.899, 668];
  const sq = ([x, y]) => `<rect x="${f(x - h)}" y="${f(y - h)}" width="${node}" height="${node}" fill="#ffffff"/>`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by generate_app_icons.js - Windows variant of range-fea.svg -->
<svg viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="background" cx="96.493" cy="926.997" r="415" gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(-1.8634597,1.8721549,-1.872152,-1.8634563,2842.291,1643.7679)">
      <stop offset="0" stop-color="#d48080"/>
      <stop offset="1" stop-color="#640a0a"/>
    </radialGradient>
    <radialGradient id="glow" cx="513.988" cy="495.659" r="235.559" gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(1.1577576,-0.00964249,0.008441,1.0134954,-85.269433,16.346034)">
      <stop offset="0" stop-color="#ffffff" stop-opacity="1"/>
      <stop offset="1" stop-color="#ffffff" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <g transform="translate(512 512) scale(${f(SCALE)}) translate(-512 -512)">
    <rect x="${MAC_MIN}" y="${MAC_MIN}" width="${MAC_SIZE}" height="${MAC_SIZE}" rx="${r}" ry="${r}" fill="url(#background)"/>
    <path d="M ${top} L ${right} L ${left} Z" fill="url(#glow)" stroke="#ffffff" stroke-width="${stroke}" stroke-linejoin="round"/>
    ${sq(top)}
    ${sq(left)}
    ${sq(right)}
  </g>
</svg>
`;
}

const SVG_LARGE = windowsSvg({ stroke: 10, node: 100 });
const SVG_SMALL = windowsSvg({ stroke: 36, node: 124 });
const SMALL_LIMIT = 32;

// Every raster output: [file, canvas size, icon size inside the canvas, vertical offset].
const ICO_SIZES = [16, 20, 24, 32, 40, 48, 64, 96, 128, 256];
const MSIX = [];
for (const s of [16, 24, 32, 48, 256]) {
  MSIX.push([`Square44x44Logo.targetsize-${s}.png`, s, s, 0]);
  // Unplated variants keep the taskbar and Start from drawing the icon on an accent plate.
  MSIX.push([`Square44x44Logo.targetsize-${s}_altform-unplated.png`, s, s, 0]);
}
MSIX.push(['Square44x44Logo.png', 44, 44, 0]);
MSIX.push(['StoreLogo.png', 50, 50, 0]);
// Tiles keep the icon smaller and slightly raised to leave room for the tile name.
MSIX.push(['Square71x71Logo.png', 71, 50, 0]);
MSIX.push(['Square150x150Logo.png', 150, 88, -8]);
MSIX.push(['Square310x310Logo.png', 310, 180, -18]);

const jobs = [
  ...ICO_SIZES.map(s => ({ key: `ico-${s}`, canvas: s, size: s, dy: 0 })),
  ...MSIX.map(([file, canvas, size, dy]) => ({ key: file, canvas, size, dy })),
];

function findBrowser() {
  const candidates = [
    'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
    'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
    'C:/Program Files/Google/Chrome/Application/chrome.exe',
  ];
  const found = candidates.find(p => fs.existsSync(p));
  if (!found) throw new Error('Microsoft Edge or Google Chrome is required to render the icons');
  return found;
}

// Draws every job onto its own canvas inside a headless browser and returns PNG data.
function render() {
  const dataUrl = svg => 'data:image/svg+xml;base64,' + Buffer.from(svg).toString('base64');
  const html = `<!doctype html><html><body><pre id="out"></pre><script>
const jobs = ${JSON.stringify(jobs)};
const sources = { large: ${JSON.stringify(dataUrl(SVG_LARGE))}, small: ${JSON.stringify(dataUrl(SVG_SMALL))} };
const load = src => new Promise((ok, fail) => { const i = new Image(); i.onload = () => ok(i); i.onerror = fail; i.src = src; });
(async () => {
  const images = { large: await load(sources.large), small: await load(sources.small) };
  const out = {};
  for (const j of jobs) {
    const c = document.createElement('canvas');
    c.width = c.height = j.canvas;
    const x = (j.canvas - j.size) / 2, y = x + j.dy;
    c.getContext('2d').drawImage(j.size <= ${SMALL_LIMIT} ? images.small : images.large, x, y, j.size, j.size);
    out[j.key] = c.toDataURL('image/png').split(',')[1];
  }
  document.getElementById('out').textContent = JSON.stringify(out);
})();
</script></body></html>`;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'range-icons-'));
  const page = path.join(tmp, 'render.html');
  fs.writeFileSync(page, html);
  try {
    const dom = execFileSync(findBrowser(), [
      '--headless=new', '--disable-gpu', '--no-first-run', `--user-data-dir=${path.join(tmp, 'profile')}`,
      '--virtual-time-budget=10000', '--dump-dom', 'file:///' + page.replace(/\\/g, '/'),
    ], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    const m = dom.match(/<pre id="out">(.+?)<\/pre>/s);
    if (!m) throw new Error('Browser did not produce the icon images');
    const out = JSON.parse(m[1]);
    for (const k of Object.keys(out)) out[k] = Buffer.from(out[k], 'base64');
    return out;
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

// ICO container with PNG compressed entries (supported since Windows Vista).
function buildIco(entries) {
  const header = Buffer.alloc(6 + 16 * entries.length);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  let offset = header.length;
  entries.forEach(([size, png], i) => {
    const e = 6 + 16 * i;
    header.writeUInt8(size >= 256 ? 0 : size, e);
    header.writeUInt8(size >= 256 ? 0 : size, e + 1);
    header.writeUInt8(0, e + 2);
    header.writeUInt8(0, e + 3);
    header.writeUInt16LE(1, e + 4);
    header.writeUInt16LE(32, e + 6);
    header.writeUInt32LE(png.length, e + 8);
    header.writeUInt32LE(offset, e + 12);
    offset += png.length;
  });
  return Buffer.concat([header, ...entries.map(([, png]) => png)]);
}

fs.writeFileSync(path.join(OUT, 'range-fea-windows.svg'), SVG_LARGE);
const images = render();
fs.writeFileSync(path.join(OUT, 'range-fea.ico'), buildIco(ICO_SIZES.map(s => [s, images[`ico-${s}`]])));
fs.mkdirSync(path.join(OUT, 'msix'), { recursive: true });
for (const [file] of MSIX) fs.writeFileSync(path.join(OUT, 'msix', file), images[file]);
console.log(`Wrote range-fea-windows.svg, range-fea.ico (${ICO_SIZES.length} sizes) and ${MSIX.length} MSIX assets`);
