version: 2
jobs:
  build:
    docker:
      - image: fedora:28
    steps:
      - checkout
      - run:
          name: Update
          command: dnf update -y
      - run:
          name: Build
          command: ./scripts/build.sh --clean && ./scripts/create_package.sh
