version: 2
jobs:
  build:
    docker:
      - image: fedora:28
    steps:
      - checkout
      - run:
          name: Update
          command: dnf update -y
      - run:
          name: Install tools
          command: dnf install -y which sudo make hostname
      - run:
          name: Install Qt
          command: dnf install -y qt qt5-qtbase-devel qt5-qtsvg
      - run:
          name: Install rpmfusion.org repository
          command: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - run:
          name: Install ffmpeg
          command: dnf install -y ffmpeg ffmpeg-devel
      - run:
          name: Build
          command: ./scripts/build.sh --clean && ./scripts/create_package.sh
