set(PROJECT_VERSION "1.0.1")
set(PROJECT_YEAR "2025")
set(PROJECT_RELEASE_DATE "2025-11-11")
set(PROJECT_PACKAGE_NAME "range-fea")
set(PROJECT_TARGET_NAME "fea")
set(PROJECT_HUMAN_NAME "Range FEA")
set(PROJECT_SHORT_NAME "FEA")
set(PROJECT_FAMILY_NAME "Range Software")
set(PROJECT_TITLE "Finite Element Analysis")
set(PROJECT_DESCRIPTION "Computer-aided engineering")
set(PROJECT_AUTHOR "Tomáš Šoltys")
set(PROJECT_AUTHOR_ADDRESS "Ke Zlatkovu 597, 25070 Odolena Voda, Czech Republic")
set(PROJECT_EMAIL "tomas.soltys@range-software.com")
set(PROJECT_WWW "https://www.range-software.com")
set(PROJECT_WWW_DOMAIN "range-software.com")
